cargo-features = ["edition2024"]

[package]
name = "neural-network"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.20.2"
matrix = { path = "../matrix" }
approx = "0.5.1"
