[package]
name = "mnist"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "1.0"
rayon = "1.8"
image = "0.24"
matrix = { path = "../matrix" }
indicatif = { version = "0.17", features = ["rayon"] }
assert_fs = "1.0"
