[package]
name = "mnist"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
image = "0.25.5"
matrix = { path = "../matrix" }
indicatif = { version = "0.17.11" }
assert_fs = "1.1.2"
