[package]
name = "consumer_binary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matrix = { path = "../matrix" }
neural-network = { path = "../neural-network" }
rand = "0.8"
indicatif = { version = "0.17", features = ["rayon"] }
